name: deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "^16"

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - uses: pnpm/action-setup@v2
        with:
          version: "^6"

      - run: make build.gh-pages

      - uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./cmd/webapp/dist
          CLEAN: true